### ISSUE TITLE
cannot work on Atom 1.17.0 beta

### ISSUE THREAD

**Issue by zzjin** [mehcode/atom-project-plus#93] opened 2017-04-13 07:53 UTC
RT
 can switch to new project but tree view was cleared.

**Comment by shemerey** [comment] 2017-04-21 09:55
same for me

**Comment by xream** [comment] 2017-04-25 09:55
This is caused by atom-project-util.

I made a new package for 1.17.0+: https://atom.io/packages/project-neue

**Comment by vinyll** [comment] 2017-05-04 08:37
Same issue here with Atom 1.17.
I've installed @xream's project-neue but it does not solve anything in my case.

Temporary solution is to move to the _project manager_ popular package in the meantime.

**Comment by mehcode** [comment] 2017-05-04 11:10
@xream Would you mind sending a PR to [atom-project-util](https://github.com/mehcode/atom-project-util) instead?  https://github.com/danielbrodin/atom-project-manager uses that as well for its project switching so if there is an issue with 1.17+ I'd be awesome to have the fix there.

---

@vinyll Since you seem to feel that is a temporary solution would you mind chiming in on #95 as to why?

**Comment by xream** [comment] 2017-05-05 01:29
@mehcode to to honest, I don't have the time. I use this api `atom.restoreStateIntoThisEnvironment(state)` in 1.17+.

**Comment by vinyll** [comment] 2017-05-05 08:04
FYI I have the same issue with Project Manager when opening in the same window; the folders tree is empty.

**Comment by mehcode** [comment] 2017-05-26 18:35
Fixed and released as v1.0

**Closed as completed by mehcode** 2017-05-26 18:35 UTC
